baseURL = 'https://compendium.codexobscura.net/'
languageCode = 'en-us'
title = "Codex Obscura"
theme = "hextra"


menu:
  main:
    - identifier: guides
      name: Guides
      pageRef: /guides
      weight: 1
    - identifier: builds
      name: Builds
      pageRef: /builds
      weight: 2
    - identifier: blog
      name: Blog
      pageRef: /blog
      weight: 3
    - identifier: more
      name: More
      weight: 4
    - name: Search
      weight: 5
      params:
        type: search
    - identifier: about
      name: About
      pageRef: /about
      parent: more
      weight: 1
    - identifier: legal
      name: Legal
      pageRef: /legal
      parent: more
      weight: 2
    - identifier: support
      name: Support
      pageRef: /support
      parent: more
      weight: 3

  sidebar:
    - identifier: more
      name: More
      params:
        type: separator
      weight: 1
    - identifier: about
      name: "About"
      pageRef: "/about"
      weight: 2
    - identifier: legal
      name: "Legal"
      pageRef: "/legal"
      weight: 3
    - identifier: support
      name: "Support"
      pageRef: "/support"
      weight: 4

params:
  description: A compendium of TTRPG guides, builds, and musings.

  externalLinkDecoration: true

  banner:
    key: 'its alive'
    message: |
      The Compendium is here! ðŸŽ‰ Discover [what's new]({{% relref "/blog" %}})

  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo.png
      # width: 40
      # height: 20
      # link: /
    width: wide

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  footer:
    enable: true
    displayCopyright: true
    displayPoweredBy: true
    width: normal

  # Display the last modification date
  displayUpdatedDate: true
  dateFormat: "January 2, 2006"

  # Display the author name of the last modified date
  displayUpdatedAuthor: false

  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content
      # full | forward | reverse | strict
      # https://github.com/nextapps-de/flexsearch/#tokenizer-prefix-search
      tokenize: forward

  blog:
    list:
      displayTags: true
      # date | lastmod | publishDate | title | weight
      sortBy: date
      sortOrder: desc # or "asc"
      # Pagination
      pagerSize: 20

    article:
      displayPagination: true

  toc:
    displayTags: true

  highlight:
    copy:
      enable: true
      # hover | always
      display: hover
  page:
    # full (100%), wide (90rem), normal (80rem)
    width: normal
    # tabs:
    #   sync: true
    contextMenu:
      enable: true
  outputs:
    page: [html, markdown]
    section: [html, rss, markdown]

  imageZoom:
    enable: true

  comments:
    enable: true
    type: giscus

    # https://giscus.app/
    giscus:
      repo: LehmanM05/codexobscura
      repoId: R_kgDORU8Yiw
      category: General
      categoryId: DIC_kwDORU8Yi84C3WON
      mapping: pathname
      strict: 1
      reactionsEnabled: 1
      emitMetadata: 0
      inputPosition: bottom
      lang: en
      # theme: noborder_dark
